[variables]
NODE_VERSION = "22.12.0"

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npm run build"]

[phases.start]
cmd = "npm run start"

[build]
ignoredPaths = [".git", "node_modules", ".nuxt", ".output"]